---
title: "UNT Research Computing Services Workshops"
description: |
  Workshops Presented at UNT by Research Computing Services
author:
  - name: Rich Herrington 
    url: 
    affiliation: University of North Texas
    affiliation_url: https://research.unt.edu/research-services/research-computing
output: 
    distill::distill_article:
      css: themes.css
---

## Workshops

### Simple Workflows on TACC LoneStar6 (Rich Herrington)

- **Materials**: [Simple Workflows on LoneStar6 LS6](https://richherr.github.io/UNT_workshops/ls6_first_job_workshop.html#/title-slide)

### Monitoring and Debugging SLURM Jobs on Lonestar6 (Rich Herrington)

- **Materials**: [Monitoring and Debugging SLURM Jobs on Lonestar6](https://richherr.github.io/UNT_workshops/ls6_job_monitoring_debugging_workshop.html)

### Modules, Compilers, and Your First C Program on Lonestar6 (Rich Herrington)
- **Materials**: [Modules, Compilers, and Your First C Program on Lonestar6](https://richherr.github.io/UNT_workshops/ls6_modules_compilers_first_c_workshop.html)

### An Introduction to Conda and Mamba on TACC LoneStar6 - Streamlining Scientific Computing with Effective Package Management (Rich Herrington)

- **Materials**: [An Introduction to Conda and Mamba on LS6](https://richherr.github.io/UNT_workshops/conda_ls6.html#/title-slide)

### An Introduction to Containers on TACC LoneStar6 - Reproducibility and Portability of Workflows (Rich Herrington)

- **Materials**: [An Introduction to Containers on LS6](https://richherr.github.io/UNT_workshops/containers_ls6.html#/title-slide)

## Fuller Length Courses 

### High Performance Computing on LoneStar6 (Rich Herrington)
- **Materials**: [An Introduction to Containers on LS6](https://richherr.github.io/hpc-course/)


